// Global Widget
import 'package:flutter/material.dart';
import 'package:ticket_app/base/res/app_styles.dart';
import 'package:ticket_app/base/widgets/big_dot.dart';

import 'app_layoutbuilder_widget.dart';

class TicketView extends StatelessWidget {
  const TicketView({super.key});

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size; //size is dynamic

    return SizedBox(
      width: size.width * 0.85,
      height: 179,
      child: Container(
        margin: EdgeInsets.only(right: 16),
        padding: EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: AppStyles.ticketBlue,
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(21),
            topRight: Radius.circular(21),
          ),
        ),
        // child: Center(child: Text("data")),
        child: Column(
          children: [
            //Show departure & destination with icons first line
            Row(
              // mainAxisAlignment: MainAxisAlignment.spaceBetween, //For complex alignment doesn't work for individual texts
              children: [
                Text(
                  "NYC",
                  style: AppStyles.headLineStyle3.copyWith(color: Colors.white),
                ),
                Expanded(child: Container()), //Expanded - Proportionally puts lots of items i.e. space between each child
                BigDot(),
                Expanded(child: Stack(children: [
                  /* How to get Dynamic Space:
                  * The dash (which we want in-between) are widgets (Any kind of thing as pixel)
                  * available space / random no. - will be given to List.generate()
                  * LayoutBuilder() - returns available space i.e. width between widgets(say BigDots)
                  * Flex() is a new widget helps to spread a line equally (- - - - -): not joined to each other - As the widgets generated by List.generate() would be sitting together not spaced (straight line not dashed),
                  * List.generate() - helps us to know how many items we want and then generates certain widgets with the help of SizedBox()
                  * SizedBox() or any other widget like Container() - provides the size of the widget generated
                  * */

                  //All the widgets in Flutter are nested
                  SizedBox(
                    // child: Text("--------------------"),
                    height: 24,
                    child: AppLayoutBuilderWidget(randomDivider: 6)
                  ),

                  Center(child: Transform.rotate(angle: 1.57, //angle is in radians
                  child: Icon(Icons.local_airport_rounded, color: Colors.white)))
                ],)), //Acc. to the no. of spaces, the no. of dots will vary & Overlapping - for Overlapping we use a special widget called as Stack Widget
                BigDot(),
                Expanded(child: Container()),
                Text(
                  "LDN",
                  style: AppStyles.headLineStyle3.copyWith(color: Colors.white),
                ),
              ],
            ),
            SizedBox(height: 3),
            //Show departure & destination names with time
            Row(
              // mainAxisAlignment: MainAxisAlignment.spaceBetween, //For complex alignment doesn't work for individual texts
              children: [
                Text(
                  "New-York",
                  style: AppStyles.headLineStyle3.copyWith(color: Colors.white, fontSize: 16),
                ),
                Expanded(child: Container()), //Expanded - Proportionally puts lots of items i.e. space between each child
                Text(
                  "8H 30M",
                  style: AppStyles.headLineStyle3.copyWith(color: Colors.white, fontSize: 16),
                ),
                Expanded(child: Container()),
                Text(
                  "London",
                  style: AppStyles.headLineStyle3.copyWith(color: Colors.white, fontSize: 16),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
