// Global Widget
import 'package:flutter/material.dart';
import 'package:ticket_app/base/res/app_styles.dart';
import 'package:ticket_app/base/widgets/app_column_text_layout.dart';
import 'package:ticket_app/base/widgets/big_circle.dart';
import 'package:ticket_app/base/widgets/big_dot.dart';
import 'package:ticket_app/base/widgets/text_style_fourth.dart';
import 'package:ticket_app/base/widgets/text_style_third.dart';

import 'app_layoutbuilder_widget.dart';


class TicketView extends StatelessWidget {
  const TicketView({super.key});

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size; //size is dynamic

    return SizedBox(
      width: size.width * 0.85,
      height: 189,
      child: Container(
        margin: EdgeInsets.only(right: 16),
        child: Column(
          children: [
            //First Row
            Container(
              padding: EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: AppStyles.ticketBlue,
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(21),
                  topRight: Radius.circular(21),
                ),
              ),
              // child: Center(child: Text("data")),
              child: Column(
                children: [
                  //Show departure & destination with icons first line
                  Row(
                    // mainAxisAlignment: MainAxisAlignment.spaceBetween, //For complex alignment doesn't work for individual texts
                    children: [
                      TextStyleThird(text: "NYC"),
                      Expanded(child: Container()), //Expanded - Proportionally puts lots of items i.e. space between each child
                      BigDot(),
                      Expanded(child: Stack(children: [
                        /* How to get Dynamic Space:
                        * The dash (which we want in-between) are widgets (Any kind of thing as pixel)
                        * available space / random no. - will be given to List.generate()
                        * LayoutBuilder() - returns available space i.e. width between widgets(say BigDots)
                        * Flex() is a new widget helps to spread a line equally (- - - - -): not joined to each other - As the widgets generated by List.generate() would be sitting together not spaced (straight line not dashed),
                        * List.generate() - helps us to know how many items we want and then generates certain widgets with the help of SizedBox()
                        * SizedBox() or any other widget like Container() - provides the size of the widget generated
                        * */

                        //All the widgets in Flutter are nested
                        SizedBox(
                          // child: Text("--------------------"),
                          height: 24,
                          child: AppLayoutBuilderWidget(randomDivider: 6)
                        ),

                        Center(child: Transform.rotate(angle: 1.57, //angle is in radians
                        child: Icon(Icons.local_airport_rounded, color: Colors.white)))
                      ],)), //Acc. to the no. of spaces, the no. of dots will vary & Overlapping - for Overlapping we use a special widget called as Stack Widget
                      BigDot(),
                      Expanded(child: Container()),
                      TextStyleThird(text: "LDN"),
                    ],
                  ),
                  SizedBox(height: 3),
                  //Show departure & destination names with time
                  Row(
                    // mainAxisAlignment: MainAxisAlignment.spaceBetween, //For complex alignment doesn't work for individual texts
                    children: [
                      SizedBox(
                        width: 100,
                        child: TextStyleFourth(text: "New-York"),
                      ),
                      Expanded(child: Container()), //Expanded - Proportionally puts lots of items i.e. space between each child
                      TextStyleFourth(text: "8H 30M"),
                      Expanded(child: Container()),
                      SizedBox(
                        width: 100,
                        child: TextStyleFourth(text: "London", align: TextAlign.end),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            //Dashed Line
            Container(
              // height: 20, 
              color: AppStyles.ticketOrange,
              child: Row(
                children: [
                  BigCircle(isRight: false),
                  Expanded(child: AppLayoutBuilderWidget(width: 6, randomDivider: 16)),
                  BigCircle(isRight: true),
                ],
              ),
            ),
            //Second Row
            Container(
              padding: EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: AppStyles.ticketOrange,
                borderRadius: BorderRadius.only(
                  bottomLeft: Radius.circular(21),
                  bottomRight: Radius.circular(21),
                ),
              ),
              // child: Center(child: Text("data")),
              child: Column(
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      AppColumnTextLayout(topText: "1 MAY", bottomText: "Date"),
                      AppColumnTextLayout(topText: "08:00 AM", bottomText: "Departure Time", alignment: CrossAxisAlignment.center),
                      AppColumnTextLayout(topText: "23", bottomText: "Number", alignment: CrossAxisAlignment.end)

                      // Expanded(child: Container()), //Expanded - Proportionally puts lots of items i.e. space between each child
                  //     Text(
                  //       "08:00 AM",
                  //       style: AppStyles.headLineStyle3.copyWith(color: Colors.white),
                  //     ),
                  //     Expanded(child: Container()),
                  //     Text(
                  //       "23",
                  //       style: AppStyles.headLineStyle3.copyWith(color: Colors.white),
                  //     ),
                  //   ],
                  // ),
                  // SizedBox(height: 3),
                  // //Show departure & destination names with time
                  // Row(
                  //   // mainAxisAlignment: MainAxisAlignment.spaceBetween, //For complex alignment doesn't work for individual texts
                  //   children: [
                  //     Text(
                  //       "Date",
                  //       style: AppStyles.headLineStyle3.copyWith(color: Colors.white, fontSize: 16),
                  //     ),
                  //     Expanded(child: Container()), //Expanded - Proportionally puts lots of items i.e. space between each child
                  //     Text(
                  //       "Departure Time",
                  //       style: AppStyles.headLineStyle3.copyWith(color: Colors.white, fontSize: 16),
                  //     ),
                  //     Expanded(child: Container()),
                  //     Text(
                  //       "Number",
                  //       style: AppStyles.headLineStyle3.copyWith(color: Colors.white, fontSize: 16),
                  //     ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
